### ISSUE TITLE
Mock: Collect Google Response for keyword (facebook, youtube)

### ISSUE THREAD

**Issue by ramsunvtech** [web-slate/simple-google-search#10]

**Comment by shangan23** [comment]
Manually created JSON files from Google search page. Added it to the `resource` folder of the package.

Each JSON has 4 main keys,

1.  total_results: Total number of results returned by the search result.
2. execution_time: Time is taken to fetch and display the result on the page in milliseconds.
3. query_string: Seach string
4. results: Array of results contains Title, URL and description for each result.

**Comment by shangan23** [comment]
Collected for all wiki mentioned key words.
